### ISSUE TITLE
NoNeedForMonad throws on partial unapply in for-comprehension

### ISSUE THREAD

**Issue by ashleymercer** [wartremover/wartremover-contrib#24]
**wartremover-contrib:** 1.1.0
**sbt:** 1.0.3
**scala:** 2.12.4

I have a case where I'm only matching part of a pattern in a for-comprehension, and `NoNeedForMonad` is failing with the following exception:

```
[error] scala.MatchError: _ (of class scala.reflect.internal.Trees$Ident)
[error]  at org.wartremover.contrib.warts.NoNeedForMonad$.$anonfun$apply$2(NoNeedForMonad.scala:19)
[error]  at scala.collection.immutable.List.map(List.scala:287)
[error]  at org.wartremover.contrib.warts.NoNeedForMonad$.$anonfun$apply$1(NoNeedForMonad.scala:18)
[error]  at scala.collection.immutable.List.flatMap(List.scala:335)
[error]  at org.wartremover.contrib.warts.NoNeedForMonad$.org$wartremover$contrib$warts$NoNeedForMonad$$processForComprehension$1(NoNeedForMonad.scala:14)
[error]  at org.wartremover.contrib.warts.NoNeedForMonad$$anon$1.traverse(NoNeedForMonad.scala:85)
[error]  ...
```

I think this code should be sufficient to trigger it:

```scala
for {
  (x, _) <- (0 to 3).zipWithIndex
} yield x
```

I'm not a scala guru by any means, but would it be sufficient to add `case Ident(...)` at line 19?

**Comment by ashleymercer** [comment]
Awesome work - thanks :)
