### ISSUE TITLE
NoNeedForMonad throws MatchError yet again

### ISSUE THREAD

**Issue by Idorobots** [wartremover/wartremover-contrib#34]
I'm getting a `MatchError` on legal code using Wartremover **v1.1.1** with SCoverage **v1.3.5** under Scala **v2.11.8** and SBT **v0.13**

Minimal test case:

`src/main/scala/warttest/WartTest.scala`

``` scala
package warttest

import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global

class WartTest {
  type Error = String

  def foo(): Future[Option[Error]] = Future(None)

  //@SuppressWarnings(Array("org.wartremover.warts.NoNeedForMonad"))
  def crash(): Future[Option[Error]] = foo().flatMap(whenOk {
    Future(None)
  })

  private def whenOk(cb: => Future[Option[Error]]): Option[Error] => Future[Option[Error]] = {
    case None => cb
    case Some(error: Error) => Future(Some(error))
  }
}
```

`src/test/scala/warttest/WartTestSpec.scala` (needed to actually run coverage instrumentation)

``` scala
package warttest

import org.scalatest.{FunSpec, Matchers}
import org.scalatest.concurrent.ScalaFutures

class WartTestSpec extends FunSpec with Matchers with ScalaFutures {
  describe("WartTest") {
    it("should compile") {
      val wt = new WartTest()
      wt.crash().futureValue shouldBe None
    }
  }
}
```

`project/plugins.sbt`

``` scala
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.3.5")

addSbtPlugin("org.wartremover" % "sbt-wartremover" % "1.1.1")
```

`project/build.properties`

``` scala
sbt.version=0.13.12
```

`build.sbt`

``` scala
name := "warttest"
organization := "none"
scalaVersion := "2.11.8"

libraryDependencies ++= Seq(
  "org.scalatest" %% "scalatest" % "2.2.6" % "test"
)

scalacOptions ++= Seq(
  "-feature", "-unchecked", "-deprecation", "-encoding", "utf8",
  "-Xfatal-warnings", "-Yno-adapted-args", "-Yrangepos", "-Ywarn-dead-code",
  "-Ywarn-inaccessible", "-Ywarn-infer-any", "-Ywarn-nullary-override",
  "-Ywarn-numeric-widen", "-Ywarn-unused", "-Ywarn-unused-import"
)

wartremoverErrors in (Compile, compile) ++= Warts.allBut(Wart.ImplicitConversion)
wartremoverErrors in (Test, test) ++= Warts.allBut(Wart.ImplicitConversion, Wart.NonUnitStatements)

addCommandAlias("testCrash", ";clean;coverage;test;coverageReport")
```

While `sbt test` runs properly, running with `sbt testCrash` results in the following stacktrace:

```
scala.MatchError: scoverage.Invoker.invoked(5, "/tmp/warttest/target/scala-2.11/scoverage-data") (of class scala.reflect.internal.Trees$Apply)
    at org.wartremover.warts.NoNeedForMonad$$anonfun$asFuncTransform$1$1.apply(NoNeedForMonad.scala:48)
    at org.wartremover.warts.NoNeedForMonad$$anonfun$asFuncTransform$1$1.apply(NoNeedForMonad.scala:48)
    at scala.collection.immutable.List.map(List.scala:273)
    at org.wartremover.warts.NoNeedForMonad$.asFuncTransform$1(NoNeedForMonad.scala:48)
    at org.wartremover.warts.NoNeedForMonad$.org$wartremover$warts$NoNeedForMonad$$processBodyArgs$1(NoNeedForMonad.scala:54)
    at org.wartremover.warts.NoNeedForMonad$$anonfun$4.apply(NoNeedForMonad.scala:59)
    at org.wartremover.warts.NoNeedForMonad$$anonfun$4.apply(NoNeedForMonad.scala:59)
    at scala.collection.immutable.List.flatMap(List.scala:327)
    at org.wartremover.warts.NoNeedForMonad$.org$wartremover$warts$NoNeedForMonad$$processFlatMapChain$1(NoNeedForMonad.scala:59)
    at org.wartremover.warts.NoNeedForMonad$$anon$1.traverse(NoNeedForMonad.scala:88)
    at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1283)
    at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1330)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
    at org.wartremover.warts.NoNeedForMonad$$anon$1.traverse(NoNeedForMonad.scala:89)
    at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1235)
    at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1330)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
    at org.wartremover.warts.NoNeedForMonad$$anon$1.traverse(NoNeedForMonad.scala:89)
    at scala.reflect.internal.Trees$$anonfun$traverseMemberDef$1$1.apply$mcV$sp(Trees.scala:1215)
    at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
    at scala.reflect.internal.Trees$class.traverseMemberDef$1(Trees.scala:1203)
    at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1328)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
    at org.wartremover.warts.NoNeedForMonad$$anon$1.traverse(NoNeedForMonad.scala:89)
    at scala.reflect.api.Trees$Traverser$$anonfun$traverseStats$1$$anonfun$apply$1.apply$mcV$sp(Trees.scala:2498)
    at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
    at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2497)
    at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1232)
    at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1330)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
    at org.wartremover.warts.NoNeedForMonad$$anon$1.traverse(NoNeedForMonad.scala:89)
    at scala.reflect.internal.Trees$$anonfun$traverseMemberDef$1$1.apply$mcV$sp(Trees.scala:1207)
    at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
    at scala.reflect.internal.Trees$class.traverseMemberDef$1(Trees.scala:1203)
    at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1328)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
    at org.wartremover.warts.NoNeedForMonad$$anon$1.traverse(NoNeedForMonad.scala:89)
    at scala.reflect.api.Trees$Traverser$$anonfun$traverseStats$1$$anonfun$apply$1.apply$mcV$sp(Trees.scala:2498)
    at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
    at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2497)
    at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1326)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
    at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
    at org.wartremover.warts.NoNeedForMonad$$anon$1.traverse(NoNeedForMonad.scala:89)
    at org.wartremover.Plugin$Traverser$$anon$1$$anonfun$go$1$1.apply(Plugin.scala:74)
    at org.wartremover.Plugin$Traverser$$anon$1$$anonfun$go$1$1.apply(Plugin.scala:74)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at org.wartremover.Plugin$Traverser$$anon$1.go$1(Plugin.scala:74)
    at org.wartremover.Plugin$Traverser$$anon$1.apply(Plugin.scala:76)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:440)
    at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:440)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:398)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:398)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1582)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
    at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
    at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
    at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
    at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
    at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
    at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
    at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
    at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
    at sbt.inc.Incremental$.compile(Incremental.scala:71)
    at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
    at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
    at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
    at sbt.Compiler$.compile(Compiler.scala:152)
    at sbt.Compiler$.compile(Compiler.scala:138)
    at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:860)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:851)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:849)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by xuwei-k** [comment]
please try 2.0.0-RC2
https://github.com/wartremover/wartremover-contrib/commit/f35668e6fcba36e216a1deae3578f2dc83eff578
